# Tên ứng dụng
spring.application.name=spring-project

# Kết nối đến MySQL từ Railway
spring.datasource.url=jdbc:mysql://metro.proxy.rlwy.net:43669/railway?useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=sPdWXQjsgUkWKrloVnbKideHzbHlqram
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Mail config
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=duc53044@donga.edu.vn
spring.mail.password=mllm urlu lifq bjhg
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Cloudinary
cloudinary.cloud-name=dpmft79zk
cloudinary.api-key=421525111334549
cloudinary.api-secret=UbRJxLSD9gQPDbeYs3qTUV8vnZM
